<?php

namespace Crossknowledge\OrderManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DetailCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailCommandeRepository extends EntityRepository
{
    public function findByCommande($commande)
    {
        $queryBuilder = $this->createQueryBuilder('c');
        $queryBuilder->where('c.commande = :commande')
                ->setParameter('commande', $commande)
                ;
        
        $query = $queryBuilder->getQuery();
        
        return $query->getResult();
    }
    
    public function findByAssignedTo($assignedTo)
    {
        $queryBuilder = $this->createQueryBuilder('c');
        $queryBuilder->where('c.assignedTo = :user AND c.type = :type ' )
                     ->setParameters(array('user' => $assignedTo, 'type' => 'DA'))
                     ;
        
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }
    
    public function findByLettrage()
    {
        $queryBuilder = $this->createQueryBuilder('c');
        $queryBuilder->where('c.lettrage != :lettrage AND c.type = :type' )
                     ->setParameters(array('lettrage' => '1', 'type' => 'OA'))
                     ;
        
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }
    
}