<?php

namespace Crossknowledge\OrderManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifRepository extends EntityRepository
{
    public function getPrice ($article, $fournisseur)
    {
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder->where('p.article = :article AND p.fournisseur = :fournisseur')
                ->setParameter('article', $article)
                ->setParameter('fournisseur', $fournisseur);
        
        $query = $queryBuilder->getQuery();
        $result = $query->getSingleResult();
        
        return $result;
                
    }
}